// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDDRInpSThxOeD14ezO8LTOHaES02umOTU",
    authDomain: "push-notification-8cf12.firebaseapp.com",
    projectId: "push-notification-8cf12",
    storageBucket: "push-notification-8cf12.firebasestorage.app",
    messagingSenderId: "789915188252",
    appId: "1:789915188252:web:4a1fb05684014e58fef3d9",
    measurementId: "G-Q2DNWYNVJB",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqbOzsVMwg9RMuslcg338Tgx1RnfDZDfw',
    appId: '1:789915188252:android:3395bc42dea32cbdfef3d9',
    messagingSenderId: '789915188252',
    projectId: 'push-notification-8cf12',
    storageBucket: 'push-notification-8cf12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJDM6B5plC0Er_KKD8dUNShhMWyM4Zkk',
    appId: '1:789915188252:ios:590f9367fae77451fef3d9',
    messagingSenderId: '789915188252',
    projectId: 'push-notification-8cf12',
    storageBucket: 'push-notification-8cf12.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJDM6B5plC0Er_KKD8dUNShhMWyM4Zkk',
    appId: '1:789915188252:ios:590f9367fae77451fef3d9',
    messagingSenderId: '789915188252',
    projectId: 'push-notification-8cf12',
    storageBucket: 'push-notification-8cf12.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDRInpSThxOeD14ezO8LTOHaES02umOTU',
    appId: '1:789915188252:web:d396b7e17b313b7cfef3d9',
    messagingSenderId: '789915188252',
    projectId: 'push-notification-8cf12',
    authDomain: 'push-notification-8cf12.firebaseapp.com',
    storageBucket: 'push-notification-8cf12.firebasestorage.app',
    measurementId: 'G-CCX7SG3JDP',
  );
}
